[server]
bind_addr = "0.0.0.0:8080"
workers = 4

[database]
url = "postgres://sentinel:sentinel123@localhost/sentinel"
max_connections = 10
min_connections = 1

[security]
jwt_secret = "your-secret-key-change-this-in-production"
token_expiry = 3600

[client_management]
heartbeat_timeout = 120
cleanup_interval = 60

[api]
rate_limit = 100
max_request_size = "10MB"

[logging]
level = "info"
file = "/var/log/sentinel-server.log"